Operation:
  # 服务器挂载路径
  # Global_server_mount_path: &root_path F:\
  Global_server_mount_path: &root_path D:\sa_data\sa_27\ #按照他的所有

  # 测试结果本地保存路径 ---> 一般是由 run scripts 导入
  # Global_Save_Dir: &root_dir D:\sa_data\exps\20221114_yolox_soft-nms_0.45\
  Global_Save_Dir: &root_dir D:\sa_data\exps\nms_thr\20221109_yolox-nano-fpn4_aware_conf015_nms_0.50\
  #组件选项
  operation_find_text_data_preprocess:
    running: false   #是否运行样本生成脚本
    sample_number: 1  #每张图片生成几个样本
    sample_ratio: 0.3
    # random: false
  operation_pic_match_data_preprocess:
    running: false  #是否运行样本生成脚本
    sample_number: 1 #每张图片生成几个样本
    sample_ratio: 0.5

  operation_grabbing_running: false   #是否运行按钮抓取组件测试
  operation_retrival_running: false     #是否运行按钮检索组件测试
  operation_ocr_common_running: false  #是否运行通用ocr common组件测试
  operation_find_text_running: false    #是否运行文本找字组件测试
  operation_pic_match_running: false    #是否运行pic_match组件测试
  operation_table_analyse_line_running: false #是否运行表格解析组件测试
  operation_table_analyse_noline_running: false  # 解析无线条表格
  operation_wx_bubble_running: false
  operation_wx_sesson_running: false
  operation_wx_msg_running: false

#########统计
  operation_grabbing_statistic: true     #是否评估按钮抓取组件性能
  operation_retrival_statistic: false      #是否评估按钮检索组件性能
  operation_ocr_common_statistic: false   #是否评估通用ocr common组件测试
  operation_find_text_statistic: false  #是否评估文本找字组件测试
  operation_pic_match_statistic: false   #是否评估图片匹配组件测试
  operation_table_analyse_line_statistic: false #是否评估表格解析组件测试
  operation_table_analyse_noline_statistic: false
  operation_wx_bubble_statistic: false   # 是否评估bubble组件性能
  operation_wx_sesson_statistic: false    # 是否评估session组件性能
  operation_wx_msg_statistic: false       # 是否评估msg组件性能


######全关
  operation_grabbing_debug: true        #是否可视化按钮抓取组件错误信息
  operation_retrival_debug: false         #是否可视化按钮检索组件错误信息
  operation_ocr_common_debug: false   #是否可视化通用ocr common组件错误信息
  operation_find_text_debug: false       #是否可视化文本找字组件错误信息
  operation_pic_match_debug: false    #是否可视化图片匹配组件错误信息
  operation_table_analyse_line_debug: false  #是否可视化表格解析组件测试
  operation_table_analyse_noline_debug: false
  operation_wx_bubble_debug: false        # 是否可视化bubble解析组件错误信息
  operation_wx_sesson_debug: false         #是否可视化sesson解析组件错误信息
  operation_wx_msg_debug: false         #是否可视化msg解析组件错误信息


  operation_different_forms_retrival_statistic: false     #是否评估按钮检索组件在遇到语义相同，但状态不同的情况下的性能 false
  operation_different_forms_retrival_debug: false        #是否可视化错误信息 false

Element_grabbing:
  Global:
    data_path: *root_path   #输入图片保存路径（sa数据格式）
    final_result_path: !join [*root_dir,Element_grabbing]      #汇总结果的保存路径

  Script_running:
    script_command: middleware_uistructed_shared_test.exe -pos imagedir savedir 1 0 #exe拿过来
    save_folder_name: yolox_predict     # 指定预测结果路径 (存放模型预测出来的json) 最好一个
    # save_folder_name: grabbing_predict #0003

  Evaluation:
    save_folder_name: grabbing_evaluation_statistics  #组件 每个app目录下统计结果的json
    img_folder_name: imgs      #输入图片路径下，图片文件夹名称
    label_folder_name: comp      #    #输入图片路径下，标签文件夹名称 
    
    # mode_0为不同元素的检测专属阈值 个性化
    # mode_1为所有元素同一阈值
    # mode_2为最新更新检测模式，默认mode2
    # debug 路径 和 mode 搭配
    mode_select: &mode mode_2
    mode_0:
      icon_iou_threshold: 0.5               #检测结果与icon标签的iou阈值
      text_iou_threshold: 0.5                #检测结果与text标签的iou阈值
      background_iou_threshold: 0            #保存与任意标签的iou都小于或者等于该阈值的检测结果
      ocr_iou_threshold: 0.1                 #ocr元素与text标签的iou阈值

    mode_1:
      max_iou: 0.5   
    
    mode_2:
      # text_iou_threshold: 0.4                #检测结果与text标签的iou阈值
      background_iou_threshold: 0            #保存与任意标签的iou都小于或者等于该阈值的检测结果
      ocr_iou_threshold: 0.1                 #ocr元素与text标签的iou阈值
      max_iou: 0.5

    mode_3:
      text_iou_threshold: 0.4
      ocr_iou_threshold: 0.1 


  Debug:
    save_folder_name: grabbing_evaluation_debug     #组件可视化结果的文件夹名称（指定后，错误可视化）

#retrival v1跑400个图像对子，v2根据icon_datalist跑已经标注为相同group按钮，没有group的就不用跑
Element_retrival:
  Global:
    
    img_folder_path: [*root_path, screen_analysis\0001_sa_v1] # D:\Test_Data\0001_sa_v1      #输入图片路径
    label_folder_path: [*root_path, screen_analysis\0004_sa_release\0006_icon_retrival_v2] #D:\Test_Data\0006_icon_retrival_v2    #检索标签所在路径

    final_result_path: [*root_dir,Element_retrival]   #汇总结果的保存路径
    retrival_v2: 1
  Script_running:
    pair_number: 400                                 #进行检索测试的图片对的数量
    #script_command: middleware_uistructed_shared_test.exe -retrival imagedir imagedir2 savedir 1 0 0 0    #v1
    script_command: middleware_uistructed_shared_test.exe -retrivalv2 srcimagepath dstimagepath savedir pos_string 1 1     #v2
    save_folder_name: retrival_result_v2       #组件预测结果保存文件名（指定后，自动生成）
    retrival_minsize: 10
  Evaluation:
    save_folder_name: retrival_v2_statistic_result               #统计结果保存文件夹名称（指定后，自动生成）
    save_different_forms_folder_name: retrival_deepLearning_statistic_result           #对语义相同但选取状态不同导致图像略微不同的标签的检索结果保存文件名
    iou_threshold: 0.1                                                                 #检索结果与标签之间的iou阈值
  Debug:
    #可视化结果保存文件名
    save_folder_name: retrival_deepLearning_debug                #可视化结果保存文件夹名称（指定后，自动生成）                                        
    save_different_forms_folder_name: different_retrival_deepLearning_debug         #可视化结果保存文件夹名称（指定后，自动生成）                

Ocr_common:
  Global:
    data_path: [*root_path, screen_analysis\0004_sa_release\0002_ocr_testdata] #D:\Test_Data\0002_ocr_testdata  #C:\Users\Hongji\Desktop\data_control\commonocr_data    #输入图片路径（sa数据格式）
    final_result_path: [*root_dir,Ocr_common]   #汇总结果的保存路径
  Script_running:
    script_command: middleware_uistructed_shared_test.exe -commonocr imagedir savedir 1 0
    save_folder_name: ocr_common_predict_20220401      #通用OCR(common)组件预测结果保存文件名（指定后，自动生成）
  Evaluation:
    #直接检索文件夹内文件
    img_folder_name: imgs     #输入图片路径下，图片文件夹名称
    label_folder_name: comp   #输入图片路径下，标签文件夹名称
    save_folder_name: ocr_common_statistic_20220401    #统计结果保存文件夹名称（指定后，自动生成）
    error_word_number: 5                              #单行文本，检测结果与标签对比，最多允许错几个字
  Debug:
    debug_folder_name: ocr_common_debug_20220401   #可视化结果保存文件夹名称（指定后，自动生成）

Find_text:
  Global:
    data_path: [*root_path, screen_analysis\0004_sa_release\0008_findtext_evaluation] #D:\Test_Data\0008_findtext_evaluation # [*root_path, screen_analysis\0004_sa_release\0008_findtext_evaluation]    #测试文件保存路径（sa数据格式）
    # script_folder: D:\download\exe_control\exe_control\gaolei\-findtext\findtext_exe\Release  #屏幕理解组件路径 feature/lei.gao/statisticOCRModel  384455b606218fcbf12bb484c5171fe292ef06e0
    final_result_path: [*root_dir,Find_text]   #汇总结果的保存路径
  Script_running:
    script_command: middleware_uistructed_shared_test.exe -findtext imagedir textdir textfilename savedir 1 0 0 10 0
    save_folder_name: find_text_predict      #组件测试结果保存文件名（指定后，自动生成）

  Evaluation:
    img_folder_name: imgs                 #输入图片路径下，图片文件夹名称
    label_folder_name: comp               #输入图片路径下，标签文件夹名称
    save_folder_name: findtext_statistics       #组件统计结果保存文件名（指定后，自动生成）
    error_word_number: 0                              #检测结果与标签的编辑距离，理解为最多错几个字
    iou_threshold: 0.1                                #检索结果与标签之间的iou阈值
  Debug:
    debug_folder_name: find_text_debug_20220401   #组件可视化结果保存文件名（指定后，自动生成）

Pic_match:
  Global:
    data_path: [*root_path, screen_analysis\0004_sa_release\0007_picmatch] #[*root_path, 0004_sa_release\0007_picmatch]    #C:\Users\Hongji\Desktop\data_control\picmatch_data   #测试文件保存路径（sa数据格式）
    # script_folder: D:\download\exe_control\exe_control\gaolei\-picmatch  #屏幕理解组件路径 feature/lei.gao/statisticOCRModel  384455b606218fcbf12bb484c5171fe292ef06e0
    final_result_path: [*root_dir,Pic_match]   #汇总结果的保存路径
  Script_running:
    script_command:  inference_picmatch_unitest.exe -picmatch imgdir sampledir savedir 1 0 0.75 #暂未添加
    save_folder_name: pic_match_predict         #组件测试结果保存文件名（指定后，自动生成）
  Evaluation:
    img_folder_name: imgs     #输入图片路径下，图片文件夹名称
    label_folder_name: comp     #输入图片路径下，标签文件夹名称
    save_folder_name: pic_match_statistic          #图片匹配组件统计结果保存文件名（指定后，自动生成）
    iou_range: [0.75,0.85,0.9,0.95]                 #检索结果与标签之间的iou阈值
    similarity_range: [0.85, 0.9]                    #检索结果与标签之间的similarity阈值
  Debug:
    debug_folder_name: pic_match_debug   #按字索图组件可视化结果保存文件名（指定后，自动生成）

Table_analyse_line:
  Global:
    data_path: [*root_path, screen_analysis\0004_sa_release\0003_table_testdata\line_testdata] # D:\Test_Data\line_testdata #  #测试文件保存路径（sa数据格式）
    # script_folder: C:\Users\Hongji\Desktop\exe_control\gaolei\-tableanalyse\4.3.4.905_277d37532b34bc42a114dfa7e641ce332d7a3607_x86_Release_Unitest_bin  #屏幕理解组件路径 feature/lei.gao/statisticOCRModel  384455b606218fcbf12bb484c5171fe292ef06e0
    final_result_path: [*root_dir,Table_analyse_line]   #汇总结果的保存路径
  Script_running:
    script_command:  libtable_analyse_shared_test.exe -table_analyse image_dir save_dir model_config_path exec_config_path 1
    save_folder_name: table_predict_20220401      #组件测试结果保存文件名（指定后，自动生成）

  Evaluation:
    img_folder_name: imgs               #图片路径
    label_folder_name: comp                #检索标签所在路径
    save_folder_name: table_statistic_20220401   #按字索图组件评估结果保存文件名
    error_word_number: 0                              #检测结果与标签的编辑距离，理解为最多错几个字
    iou_threshold: 0.1                                #检索结果与标签之间的iou阈值
    iou_range: [ 0.75,0.85,0.9,0.95 ]                 #检索结果与标签之间的iou阈值(后面的接口，暂不使用)
    similarity_range: [ 0.85, 0.9 ]                    #检索结果与标签之间的similarity阈值(后面的接口，暂不使用)
  Debug:
    debug_folder_name: table_debug_20220401   #按字索图组件评估结果保存文件名

Table_analyse_noline:
  Global:
    data_path: [*root_path, screen_analysis\0004_sa_release\0003_table_testdata\noline_testdata]  #测试文件保存路径（sa数据格式）
    # script_folder: C:\Users\Hongji\Desktop\exe_control\gaolei\-tableanalyse\4.3.4.905_277d37532b34bc42a114dfa7e641ce332d7a3607_x86_Release_Unitest_bin  #屏幕理解组件路径 feature/lei.gao/statisticOCRModel  384455b606218fcbf12bb484c5171fe292ef06e0
    final_result_path: [*root_dir,Table_analyse_noline]   #汇总结果的保存路径
  Script_running:
    script_command:  libtable_analyse_shared_test.exe -table_analyse image_dir save_dir model_config_path exec_config_path 1
    save_folder_name: table_predict_20220401      #组件测试结果保存文件名（指定后，自动生成）

  Evaluation:
    img_folder_name: imgs               #图片路径
    label_folder_name: comp                #检索标签所在路径
    save_folder_name: table_statistic_20220401   #按字索图组件评估结果保存文件名
    error_word_number: 0                              #检测结果与标签的编辑距离，理解为最多错几个字
    iou_threshold: 0.1                                #检索结果与标签之间的iou阈值
    iou_range: [ 0.75,0.85,0.9,0.95 ]                 #检索结果与标签之间的iou阈值(后面的接口，暂不使用)
    similarity_range: [ 0.85, 0.9 ]                    #检索结果与标签之间的similarity阈值(后面的接口，暂不使用)
  Debug:
    debug_folder_name: table_debug_20220401   #按字索图组件评估结果保存文件名

WxBubble:
  Global:
    data_path: [*root_path, screen_analysis\0004_sa_release\0004_wx_testdata] # D:\download\qiyeweixin\qw\qiyewx_data #   #测试文件保存路径（sa数据格式）
    # script_folder: D:\download\qiyeweixin\0008_component_test\0008_component_test\unittest  #屏幕理解组件路径 feature/lei.gao/statisticOCRModel  384455b606218fcbf12bb484c5171fe292ef06e0
    final_result_path: [*root_dir,WxBubble]  #保存汇总结果的路径
  Script_running:
    script_command: middleware_uistructed_shared_test.exe -wx_bubble imagedir savedir 1 0 
    save_folder_name: wx_bubble_predict_20220718      #按字索图组件测试结果保存文件名

  Evaluation:
    img_folder_name: imgs                 #图片路径
    label_folder_name: comp                #检索标签所在路径
    save_folder_name: wx_bubble_statistic_20220718   #按字索图组件评估结果保存文件名
    error_word_number: 0                              #检测结果与标签的编辑距离，理解为最多错几个字
    iou_threshold: 0.5
    errorfile_name: content_compare_fail
  Debug:
    debug_folder_name: D:\download\qiyeweixin\debug

WxSesson:
  Global:
    data_path: [*root_path, screen_analysis\0004_sa_release\0004_wx_testdata] # D:\download\qiyeweixin\qw\wx_sesson_data #  #D:\download\qiyeweixin\qw\wx_sesson_data   #测试文件保存路径（sa数据格式）
    # script_folder: D:\download\qiyeweixin\0008_component_test\0008_component_test\unittest  #屏幕理解组件路径 feature/lei.gao/statisticOCRModel  384455b606218fcbf12bb484c5171fe292ef06e0
    final_result_path: [*root_dir,WxSesson]  #保存汇总结果的路径
  Script_running:
    script_command: middleware_uistructed_shared_test.exe -wx_sesson imagedir savedir 1 0
    save_folder_name: wx_sesson_predict_20220718      #按字索图组件测试结果保存文件名

  Evaluation:
    img_folder_name: imgs                 #图片路径
    label_folder_name: comp                #检索标签所在路径
    save_folder_name: wx_sesson_statistic_20220718  #按字索图组件评估结果保存文件名
    error_word_number: 0                              #检测结果与标签的编辑距离，理解为最多错几个字
    iou_threshold: 0.5
    errorfile_name: content_compare_fail
  Debug:
    debug_folder_name: D:\download\qiyeweixin\debug

WxMsg:
  Global:
    data_path: [*root_path, screen_analysis\0004_sa_release\0004_wx_testdata] #D:\download\qiyeweixin\qw\wx_msg_data # [*root_path, screen_analysis\0004_sa_release\0004_wx_testdata]  # D:\download\qiyeweixin\qw\wx_msg_data   #测试文件保存路径（sa数据格式）
    # script_folder: D:\download\qiyeweixin\0008_component_test\0008_component_test\unittest  #屏幕理解组件路径 feature/lei.gao/statisticOCRModel  384455b606218fcbf12bb484c5171fe292ef06e0
    final_result_path: [*root_dir,WxMsg]  #保存汇总结果的路径
  Script_running: #跑脚本的
    script_command: middleware_uistructed_shared_test.exe -wx_msg imagedir savedir 1 0
    save_folder_name: wx_msg_predict_20220620      #按字索图组件测试结果保存文件名

  Evaluation: #只关注这个
    img_folder_name: imgs                 #图片路径
    label_folder_name: comp                #检索标签所在路径
    save_folder_name: wx_msg_statistic_20220620   #按字索图组件评估结果保存文件名
    error_word_number: 0                              #检测结果与标签的编辑距离，理解为最多错几个字
    iou_threshold: 0.5
    errorfile_name: content_compare_fail
  Debug:
    debug_folder_name: D:\download\qiyeweixin\debug

###
Component_operating:
  frameworkType: 1
  algorithmId: 30                 
  log_path: "d:/logs"

  #算法内部OPENMP的并行数量
  numThread: 8

  #模型的绝对路径
  #dbnet_model: "../models/denet_mobilenet_v3.onnx"
  dbnetModelPath: "./models/model_mutil_v1.onnx"
  buttonFeatureModelPath: "./models/button_feature.onnx"
  crnnModelPath: "./models/general_rec_crnn.onnx"
  crnnModelPathOnnxruntime: "./models/general_rec_crnn.onnx"
  crnnKeyPath: "./models/mmocr_charset"
  buttonClassifyModelPath: "button_classification_cnn_20210305.onnx"

  #dbnet 检测参数
  resizeHeight: 1088
  resizeWidth: 1920
  boxScoreThresh: 0.5
  boxThresh: 0.3
  unClipRatio: 2.0

  #yolox 检测参数

  #传统的按钮检测参数
  minLineLen: 41
  minButtonSize: 50
  maxButtonSize: 500000
  resizeScale: 1

  #按钮特征匹配参数
  similarThresh: 0.8

  #按钮分类参数
  whRatio: 3.0

  #图片匹配参数
  bAutoScale: 0




